# Generated by Django 3.1.3 on 2021-01-02 13:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201226_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_bn',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='contact_en_us',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_bn',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_en_us',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
